---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-test
  name: docker-test
  namespace: dev
spec:
  ports:
  - port: 8050
    protocol: TCP
    targetPort: 80
  selector:
    app: docker-test
  #type: ClusterIP
  type: NodePort